apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: davidgehrig-com
  namespace: default
spec:
  secretName: davidgehrig-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-davidgehrig-com
  commonName: '*.davidgehrig.com'
  dnsNames:
  - '*.davidgehrig.com'
  acme:
    config:
    - dns01:
        provider: azure-prod-davidgehrig-com
      domains:
      - '*.davidgehrig.com'