apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: davidgehrig-com
  namespace: default
spec:
  secretName: davidgehrig-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-davidgehrig-com
  commonName: '*.davidgehrig.com'
  dnsNames:
  - davidgehrig.com
  - '*.davidgehrig.com'