apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nadineunddavid-ch
  namespace: default
spec:
  secretName: nadineunddavid-ch-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-nadineunddavid-ch
  commonName: '*.nadineunddavid.ch'
  dnsNames:
  - '*.nadineunddavid.ch'