apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nadineunddavid-ch
  namespace: default
spec:
  secretName: nadineunddavid-ch-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-nadineunddavid-ch
  commonName: '*.nadineunddavid.ch'
  dnsNames:
  - '*.nadineunddavid.ch'
  acme:
    config:
    - dns01:
        provider: azure-prod-nadineunddavid-ch
      domains:
      - '*.nadineunddavid.ch'